name: color_blindness
description: Color Blindness on Flutter. Works with either color scheme or individual colors.
version: 0.1.2
homepage: https://github.com/bernaferrari/ColorBlindnessFlutter

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
