name: color_blindness
description: Color Blindness on Flutter. Works with either color scheme or individual colors.
version: 0.1.0
homepage: https://github.com/bernaferrari/ColorBlindnessFlutter

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
